# Site settings
title: 2017 NSA Competition
description: 2017 NSA Competition
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://psusecurity.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-hacker
