# Site settings
title: 2018 Penn State Cybersecurity Competition
description: 2017 NSA Competition
show_downloads: false
url: "http://psusecurity.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-hacker
